// AUTO-GENERATED by scripts/update-results.mjs — do not edit by hand.
// Real 2026 FIFA World Cup results from Naver Sports, refreshed at build time.
// Source: https://m.sports.naver.com/fifaworldcup2026/record

export interface SnapshotResult {
  home: number;
  away: number;
}

/** KST date this snapshot was built — used as the app's "today". */
export const SNAPSHOT_DATE = "2026-06-18";

export const RESULTS: Record<string, SnapshotResult> = {
  "M1": { home: 2, away: 0 },
  "M2": { home: 2, away: 1 },
  "M3": { home: 1, away: 1 },
  "M4": { home: 4, away: 1 },
  "M5": { home: 0, away: 1 },
  "M6": { home: 2, away: 0 },
  "M7": { home: 1, away: 1 },
  "M8": { home: 1, away: 1 },
  "M9": { home: 1, away: 0 },
  "M10": { home: 7, away: 1 },
  "M11": { home: 2, away: 2 },
  "M12": { home: 5, away: 1 },
  "M13": { home: 1, away: 1 },
  "M14": { home: 0, away: 0 },
  "M15": { home: 2, away: 2 },
  "M16": { home: 1, away: 1 },
  "M17": { home: 3, away: 1 },
  "M18": { home: 1, away: 4 },
  "M19": { home: 3, away: 0 },
  "M20": { home: 3, away: 1 },
  "M21": { home: 1, away: 0 },
  "M22": { home: 4, away: 2 },
  "M23": { home: 1, away: 1 },
  "M24": { home: 1, away: 3 },
};
